# Generated by Django 3.2.7 on 2021-10-12 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_course',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
