# Generated by Django 3.2.7 on 2021-10-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Trainer',
        ),
    ]
